name: notex # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple notepad app written in C++! # 79 char long summary
description: |
  Notex is a very simple, bare-bones, graphical text editor written in C++. It is
  basically the equivalent of Windows Notepad but for Linux!
title: Notex
website: https://github.com/IsakTheHacker/notex
source-code: https://github.com/IsakTheHacker/notex.git
issues: https://github.com/IsakTheHacker/notex/issues
license: MIT

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: arm64
    run-on: arm64

  - build-on: i386
    run-on: i386

apps:
  notex:
    command: bin/notex
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa-gl:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/xorg:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio/
      LIBGL_DRIVERS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
    plugs:
      - opengl
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - cups-control
      - gsettings
      - home

parts:
  notex:
    source: https://github.com/IsakTheHacker/notex.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      mkdir -p bin
    plugin: make
    build-packages:
      - libsfml-dev
    stage-packages:
      - libsfml-dev
    stage:
      - assets/*
